export const copy = {
en: {
local:'Made here. Stays here.',eyebrow:'LESS SCROLLING. MORE FEELING.',headline:'Wish you could<br><em>hear this.</em>',intro:'A little sound. A few words. Something to keep.',preview:'YOUR LITTLE PIECE OF THE WORLD',previewLive:'LIVE PREVIEW',underCard:'Some moments deserve more than a photo.',openPreview:'Open your postcard ↗',privacy:'Your audio stays in your browser. No uploads, no account, no tracking.',make:'Make it yours',sound:'A little sound',drop:'Drop a sound here',formats:'or choose a file · up to 25 MB',noSound:'Nothing handy?',demo:'Try a little daydream ♪',start:'Start · seconds',end:'End · seconds',trimHint:'Keep a moment of up to 30 seconds.',words:'A few words',to:'To',from:'From',message:'Your note',place:'A little sound from',paper:'Pick your paper',cream:'Butter',rose:'Blush',blue:'Air mail',night:'Midnight',download:'Save your sound postcard',exportHint:'One .html file. Sound included. Yours to send.',shareNote:'Send the file to someone. They can download it and open it in a browser, even offline. Chat previews may not play it.',footer:'A small thing, made with love.',recipientView:"Just as they'll receive it",close:'Close ×',recipientNote:'A little moment, ready to travel.',loading:'Opening your sound…',ready:'Your sound is ready. Make this moment yours.',demoName:'A little daydream · original demo',replace:'Choose or drop another sound',source:'source',selected:'selected',tooBig:'Choose a file smaller than 25 MB.',tooLong:'Please choose a recording under 5 minutes, then keep up to 30 seconds.',tooShort:'This sound is too short. Choose at least 0.2 seconds.',channels:'Please use a mono or stereo recording.',invalidFile:"That sound couldn't be opened. Try a WAV, MP3, or M4A file supported by your browser.",invalidTrim:'Choose a valid section of 0.2–30 seconds within your recording.',saved:'Your postcard is saved. Send the .html file, with a little love.',exporting:'Tucking the sound into your postcard…',exportError:"Couldn't save the postcard. Please try again.",empty:'Add a sound or try the little daydream first.',sampleMessage:"I saved a little piece of today for you.\nClose your eyes. You're here with me.",sampleRecipient:'you',sampleSender:'me',samplePlace:'somewhere lovely',dear:'Dear',withLove:'With love,',listen:'Press play. Be here for a moment.',made:'A little closer, wherever you are.',size:'Sound included · about',localFile:'Local audio',play:'Play sound',pause:'Pause sound',seek:'Playback position',wave:'Audio waveform',editorLabel:'Create your postcard',previewLabel:'Postcard preview',paperLabel:'Paper color'
},
zh: {
local:'在这里制作，留在你手里。',eyebrow:'把平凡的一刻，寄给特别的人。',headline:'真想让你<br><em>也听见。</em>',intro:'一小段声音，几句心里话，一张值得留下的明信片。',preview:'你的小小世界，装进一张明信片',previewLive:'实时预览',underCard:'有些时刻，照片还不够。',openPreview:'打开这张明信片 ↗',privacy:'声音只在你的浏览器里处理。不上传，无需账户，没有追踪。',make:'把这一刻，寄出去',sound:'一小段声音',drop:'把声音放在这里',formats:'或点击选择文件 · 最大 25 MB',noSound:'手边没有录音？',demo:'试试这一小段白日梦 ♪',start:'起点 · 秒',end:'终点 · 秒',trimHint:'留住最多 30 秒的小小瞬间。',words:'几句心里话',to:'寄给',from:'来自',message:'想说的话',place:'声音来自',paper:'挑一张信纸',cream:'奶油',rose:'脸红',blue:'晴空',night:'午夜',download:'保存这张声音明信片',exportHint:'一个 .html 文件，装着声音，也装着心意。',shareNote:'把文件发给对方，下载后用浏览器打开即可离线聆听。聊天软件的预览可能无法播放。',footer:'小小的东西，认真地喜欢。',recipientView:'对方收到时，就是这样。',close:'关闭 ×',recipientNote:'这一刻，准备好出发了。',loading:'正在打开你的声音……',ready:'声音准备好啦。把这一刻写成你的样子吧。',demoName:'一小段白日梦 · 原创示例',replace:'点击或拖入另一段声音',source:'原音频',selected:'已选',tooBig:'请选择小于 25 MB 的文件。',tooLong:'请选择 5 分钟以内的录音，再截取最多 30 秒。',tooShort:'这段声音太短啦，请选择至少 0.2 秒的声音。',channels:'请选择单声道或立体声录音。',invalidFile:'这段声音暂时打不开，请试试浏览器支持的 WAV、MP3 或 M4A 文件。',invalidTrim:'请在录音范围内选择 0.2–30 秒的有效片段。',saved:'明信片保存好啦。把这个 .html 文件，连同一点心意送出去吧。',exporting:'正在把声音装进明信片……',exportError:'暂时没能保存，请再试一次。',empty:'先放进一段声音，或试试这一小段白日梦。',sampleMessage:'给你留了一小片今天。\n闭上眼睛，就当你也在我身边。',sampleRecipient:'你',sampleSender:'我',samplePlace:'一个可爱的地方',dear:'亲爱的',withLove:'来自',listen:'按下播放，听见这一刻。',made:'把这一刻，寄给你。',size:'已装入声音 · 约',localFile:'本地音频',play:'播放声音',pause:'暂停声音',seek:'播放进度',wave:'声音波形',editorLabel:'制作声音明信片',previewLabel:'明信片预览',paperLabel:'信纸颜色'
}
};

